### PR TITLE
Change studioqt to use relative imports

### PR DESCRIPTION
**Pull request by krathjen**

### CODE REVIEW

**Comment by kalemas** [comment]
Hm )) I m avoiding explicit relative imports in my projects, do not remember why. Are they py3 compatible?

I just tested this in out environment and module reloading was just fine (as it was with [refactor/studiolibrary).](https://github.com/krathjen/studiolibrary/tree/refactor/studiolibrary) It looks like we removed/changed any timer in recent commit. Probably that timer was triggered from C++ stack in corrupted namespace after we do `reload(studiolibrary)`.

**Comment by krathjen** [comment]
Thanks for having a look @kalemas.

I think it is recommended for complex packages to have absolute imports, however, using explicit relative imports should be fine in Python 3.

Please let me know if you find anything different.

Kurt

**Comment by kalemas** [comment]
@krathjen you will not be able to do testing as you like (inside `__main__`) with relative imports as they work only inside a package. I'd prefer absolute imports  still.

**Comment by krathjen** [comment]
Closing this pull request for now. Will probably move the "studioqt" module to "studiolibrary.qt" in the future.

**Pull request closed without merging**
