### PR TITLE
Fix windows unicode errors and windows nfs bug

### PR DESCRIPTION
**Pull request by Eiken**
Fixes windows unicode errors we noticed and bug #315

### CODE REVIEW

**Comment by Eiken** [comment]
@krathjen you can take which commits you want here. The windows compatibility issues is not super tested but we are running with them now

**Comment by krathjen** [comment]
Thank you very much @Eiken! :)

**Comment by krathjen** [comment]
Just letting you know that were getting the following error when using python 3...

**Comment by Eiken** [comment]
We got errors on windows. This and spme others

```
# Traceback (most recent call last):
#   File "D:\studiolibrary\studiolibrary\widgets\sidebarwidget\sidebarwidget.py", line 563, in selectionChanged
#     self.parent().search()
#   File "D:\studiolibrary\studiolibrary\widgets\sidebarwidget\sidebarwidget.py", line 263, in search
#     self.dataset().search()
#   File "D:\studiolibrary\studiolibrary\library.py", line 655, in search
#     self._results = self.findItems(self.queries())
#   File "D:\studiolibrary\studiolibrary\library.py", line 570, in findItems
#     match = self.match(item.itemData(), queries)
#   File "D:\studiolibrary\studiolibrary\library.py", line 851, in match
#     itemValue = six.u(data)
#   File "D:\studiolibrary\studiovendor\six.py", line 668, in u
#     s = unicode(s, encoding)
# TypeError: coercing to Unicode: need string or buffer, dict found
```

**Comment by Eiken** [comment]
I don't think that encoding dance that is being done in utils.py should be needed. Can I run the interface standalone with python3 in any way? Don't have any maya build with python3 to test with yet.

**Comment by krathjen** [comment]
Interesting... That line fixed a similar error we were having. We;re also using python2 and maya 2019.

**Comment by krathjen** [comment]
What about if you change that line in six to the following instead?

```
        if not isinstance(s, basestring):
            s = unicode(s, encoding)

yea, the 'unicode_escape` dance is frustrating but at the time it solved an issue we were having with certain non-English characters. It would be good to drop it if we can.

**Comment by krathjen** [comment]
I pushed some changes to master.

- Removed the `unicode_escape` code 
- Fixed python 3 errors we were seeing

Thanks again for your help and please let me know if you have any issues.

**Pull request merged**
