### PR TITLE
Reconstruct node instead of duplicating when saving animation

### PR DESCRIPTION
**Pull request by kalemas**
We started to do locking rig containers (Maya Assets) and found that we can not save animation items because outgoing connections to locked attribute can not be disconected. I suggest following way to prepare node for animation to paste.

### CODE REVIEW

**Comment by krathjen** [comment]
Thanks for this. I'll have a look soon.

**Comment by krathjen** [comment]
Hey @kalemas,

Sorry for taking so long to look at this pull request, I needed to have a closer look and make sure everything was working as expected.

After having a look I noticed that one of the test files was not set up correctly. I've added a commit to the branch/pull request which should fix this test.

So now if you run the following tests, you will notice that the changes in this pull request break vector attributes. 

```
import studiolibrary
import mutils.tests
mutils.tests.run()
```

I also tried to make a test that breaks the disconnectAll function that you mention in the comments.

Do you mind recreating the error/setup in the following maya file. This file contains a sphere that is referenced in the test_anim.ma (same directory). The test_anim.ma file is used by the tests to transfer animation between the referenced srcSphere and the dstSphere. Once you have made the changes, save the file and run the tests again and see if they break.

```studiolibrary/packages/mutils/tests/data/sphere.ma```

Sorry that the information on the tests is limited.

Thanks again and please let me know if you need more information.

Kurt

**Comment by krathjen** [comment]
Sorry... I closed the pull request by accident.

**Comment by kalemas** [comment]
@krathjen take a look please

**Comment by krathjen** [comment]
Hey @kalemas,

Thanks for updating the pull request. I see the issue now. It's annoying that we cannot disconnect that connection.

All the changes look great. The only suggestion I would make is making a function called "duplicateTransform" that contains the code you have added. What do you think?

Either way, I'm happy for you to merge these changes. Otherwise, I can merge them over the next few days.

Thanks again,

Kurt

**Comment by kalemas** [comment]
@krathjen do you mean to implement functionality of true duplicating a transform without connections? Because i do minimal reconstruction that is suitable for copy/paste animation, without copying attribute limits or parenting that is expected with regular duplicate or whatever else.

**Comment by krathjen** [comment]
Hey @kalemas,

Sorry that this pull request is still open. 

I'm hesitant to merge this code as I would like to test this issue more.

I actually think its okay to remove the 'mutils.disconnectAll' line instead of making the other changes. The tests (including the one you added) seem to work fine without this line and I also cannot see this causing any issue.

Please let me know your thoughts.

Cheers,

Kurt

**Comment by krathjen** [comment]
Reopen until there is an option (config) to disable 'mutils.disconnectAll' in the animation save method.

**Comment by krathjen** [comment]
Hey @kalemas,

Thanks again for looking at this issue.

I've added the following variable for testing a fix for the issue.

Version 2.4.0.b17 (master branch) has the change.

Let me know if this fixes your issue.

Cheers,

Kurt
 

```python
import studiolibrary

import mutils.animation
mutils.animation.FIX_SAVE_ANIM_REFERENCE_LOCKED_ERROR = True

import mutils.tests
mutils.tests.run()
```

**Comment by krathjen** [comment]
Closing this pull request for now, however, feel free to reopen this issue if the suggested fix doesn't work.

A variable to fix this issue is now available in version 2.4.0.b17+.

```python
import studiolibrary
import mutils.animation

mutils.animation.FIX_SAVE_ANIM_REFERENCE_LOCKED_ERROR = True
```

**Pull request closed without merging**
