### PR TITLE
Fix listdir on Windows share with no permission to list root

### LINKED ISSUE #435: listdir exception on Windows share
Hi, we encounter following issue if Library is hosted on windows share if there is no permission to list root folder:

image

I m not sure the reasons it occur and how it should be handled, @krathjen do you?

### PR DESCRIPTION
**Pull request by kalemas**
Not sure it is correct exception handling, and not sure it is `listdir()`, it just raises same exception as `scandir` but not `listdir` so i do not realize something here.

Closes #435

### CODE REVIEW

**Comment by krathjen** [comment]
Thanks @kalemas 

Your changes look good. I actually haven't seen this error, so I might have a closer look before merging these changes.

Cheers,

Kurt

**Comment by kalemas** [comment]
I think StudioLibrary should not try to deal with anything above library root folder. As i understand, when i open library item, it should know, whether it have mirror table in parent folders. But it is not supposed that mirror table will be outside the library.

And as library convert path to real that may be network share, it becomes unsafe to do listing in sense of permissions. So i will try to limit depth or add stop folder to `walkup`.

**Comment by kalemas** [comment]
@krathjen What if `studiolibrary.walkup()` will stop on folders with `.studiolibrary`, is it clear sign of library root?

**Comment by krathjen** [comment]
Hey @kalemas ,

I think what you have looks good.  The `.studiolibrary` folders are used in subdirectories from the root, so it might not be the best condition. It's also possible to have sub-libraries, which makes the logic a little tricky in this case.

Is the exception handling you added causing issues?

Thanks,

Kurt

**Comment by kalemas** [comment]
> Is the exception handling you added causing issues?

@krathjen No i see no any tangible issue, exception handling is something should be generally avoided, and i may prefer passing stop folder in this case but it is up to your preference. May be PermissionError should be handled as well.

**Comment by krathjen** [comment]
Hey @kalemas, 

Thanks again,

I finally had a quick look at recreating this issue but I didn't have any luck.  :(

I like how you moved the conditions from the nested structure. It might also be nice to do the same for the exception condition. What do you think? for example...
``` code
try:
    filenames = os.listdir(folder)
except OSError as e:
    if 'An unexpected network error occurred' in e.strerror:
        continue
    raise
```

**Comment by kalemas** [comment]
It would be device or system specific, in our scenario `\\fs\share\root\library` - `share` have no permission to list folder but have permission to traverse folders and `root` have both permissions. Listing `share` caused unexpected network error.

I also pushed skipping PermissionError as it definitely expected.

**Comment by kalemas** [comment]
I cant get `OSError('An unexpected network error occurred')` with same (should be) permission setup on same share. Only `PermissionError` so that part would be removed from PR, leave only `PermissionError` handling.

**Comment by kalemas** [comment]
So i think we should not add handling that cant be reproduced and leave only handling of cases that are definitely expected.

**Review by krathjen — APPROVED** [review]
Looks good! Thanks for the update.

**Pull request merged**
