### PR TITLE
Support proxy attributes.

### PR DESCRIPTION
**Pull request by tokejepsen**
The issue we were facing was that we were using proxy attributes to clone an attribute to multiple controls. When exporting the animation the code wanted to rename a referenced controller.

Filter to animCurves only when exporting animation, to support proxy attributes.

Here is the code to make proxy attributes: http://www.cultofrig.com/2017/07/23/pilot-season-day-17-maya-assets-encapsulation/

### CODE REVIEW

**Comment by krathjen** [comment]
Thanks for this pull request. :)

I've only had a quick look but I noticed that we still need to add the dstCurve to the dstCurves for clean up otherwise they may get left in the scene.

I've put together an example below that might avoid this.

Let me know what you think.

Thanks again!

```python 
# EXAMPLE: This has not been tested!

                        # Filter to only animCurves since you can have proxy attributes
                        # if not maya.cmds.nodeType(dstCurve).startswith("animCurve"):
                        #    continue

                        if dstCurve:
                            dstCurve = maya.cmds.rename(dstCurve, "CURVE")
                            srcCurve = mutils.animCurve("%s.%s" % (name, attr))

                            dstCurves.append(dstCurve)

                            isValidCurve = maya.cmds.nodeType(dstCurve).startswith("animCurve")
                            isValidCurve = isValidCurve and maya.cmds.keyframe(
                                                        dstCurve, 
                                                        query=True, 
                                                        time=(start, end), 
                                                        keyframeCount=True
                                                        )

                            if isValidCurve:
                                preInfinity = maya.cmds.getAttr(srcCurve + ".preInfinity")
                                postInfinity = maya.cmds.getAttr(srcCurve + ".postInfinity")
                                curveColor = maya.cmds.getAttr(srcCurve + ".curveColor")
                                useCurveColor = maya.cmds.getAttr(srcCurve + ".useCurveColor")

                                maya.cmds.setAttr(dstCurve + ".preInfinity", preInfinity)
                                maya.cmds.setAttr(dstCurve + ".postInfinity", postInfinity)
                                maya.cmds.setAttr(dstCurve + ".curveColor", *curveColor[0])
                                maya.cmds.setAttr(dstCurve + ".useCurveColor", useCurveColor)

                                self.setAnimCurve(name, attr, dstCurve)
                                maya.cmds.cutKey(dstCurve, time=(MIN_TIME_LIMIT, start - 1))
                                maya.cmds.cutKey(dstCurve, time=(end + 1, MAX_TIME_LIMIT))
                                validAnimCurves.append(dstCurve)
```

**Comment by tokejepsen** [comment]
Sorry about that!

Are these tests manual, or something we can run to test studiolibrary? Maybe some continuous integration testing might be an idea?

**Comment by tokejepsen** [comment]
Great! What happens now?

Need anything else from me?

**Comment by krathjen** [comment]
All good! I'll merge it and make a new release. Thanks again!

**Comment by tokejepsen** [comment]
No problem :) Thanks for having this great open source tool!

**Pull request merged**
