### PR TITLE
Add relative posing support to apply a pose relative to the selected …

### PR DESCRIPTION
**Pull request by chadmv**
Add relative posing support to apply a pose relative to the selected control

Allows users to place a control, for example the ik foot, and then apply
a pose so that the selected control, in this example the ik foot,
remains in place and the pose is applied relative to that location.

Relative Posing

In order for this to work, two new options were added:

-  A boolean toggle called "relativeTo"  to enable this functionality
- A file path to a text file listing the top level controls and controls that have a
 world space constraint.

The text file listing the controls is required in order to properly place
controls. It should list a control per line and list the top level controls
and controls with a world space constraint option. For
example with the Mery rig, we list the main torso control, the upper arm fk
controls because they have a global space switch option, the pole vector controls,
the ik controls, the head, and eyes.

```
Mery_ac_cn_torso
Mery_ac_lf_uparm
Mery_ac_rg_uparm
Mery_ac_lf_elbowPivot
Mery_ac_rg_elbowPivot
Mery_ac_lf_ikhand
Mery_ac_rg_ikhand
Mery_ac_cn_head
Mery_ac_cn_eyes
Mery_ac_lf_kneePivot
Mery_ac_lf_ikfoot
Mery_ac_rg_kneePivot
Mery_ac_rg_ikfoot
```

The control list definition file could not be automated because
controls could be driven by arbitrary networks.

To use the functionality, enable the relativeTo option and set the
path to the control list. Then select the control you want to use
as the "anchor" and apply the pose. If you get an unexpected
result, verify that all top level and world constrained controls are listed.
Relative posing also works with mirroring.

### CODE REVIEW

**Comment by krathjen** [comment]
Thanks again @chadmv. I still haven't had a chance to test this one, but it does look great. I'll let you know soon.

**Comment by adamjrbaker** [comment]
Any update on the testing of this feature?

**Comment by JonasOuellet** [comment]
Hello @chadmv this works well!  Thanks for the feature :)

I found out a bug thought.  The paste relative will not work if you paste the same pose more than one time on the same frame with the same selection.  It will always snap back to the result of the first paste.  I suppose you use some sort of caching.

Thanks again the feature is very helpful !

**Comment by fdrom00** [comment]
It would be great if the "relative to" was simply relative to "the last control selected"

**Pull request merged**
