### PR TITLE
Add root namespace (':') to the return of getAll to fix ValueError when applying pose

### PR DESCRIPTION
**Pull request by cfujiwara-rfx**
@krathjen ,
This is the change we made to fix the error:

ValueError: The namespace ":" does not exist in the scene! P​lease choose a namespace which exists.

It happens when we try applying a pose to a character that does not have a namespace.

### CODE REVIEW

**Comment by krathjen** [comment]
Hi @cfujiwara-rfx,

We really appreciate the merge request. Thank you!

The changes look good, however, I'm wondering how you were getting this error.

I can recreate the error if I manually enter `:` in the namespace field but I guess you're not doing this.

Also saving and applying a pose without a namespace seems to work in version 2.8.0. I also tested applying a pose that contains a namespace to a character that doesn't have a namespace.

Do you know how `:` is ending up in the namespace field?

Thanks again,

Kurt

**Comment by cfujiwara-rfx** [comment]
Hi @krathjen ,

So, yeah, we are entering the ":"  like this:
`item = poseitem.PoseItem(path)`
`item.load(namespaces=':')`

If we do not enter anything, it does not find the controllers, I think it is because the pose was exported with namespace and it is being imported in a rig that is not referenced in the file and does not have namespace? This is the error if we do not enter anything or an empty list for the namespace:
```
Traceback (most recent call last):
  File "/studiolibrary/src/mutils/attribute.py", line 260, in type
    self._type = maya.cmds.getAttr(self.fullname(), type=True)
ValueError: No object matches name: namespace:L_fringeTweaker_7_CON.rotateZ # 
# Error: mutils.attribute : Cannot GET attribute TYPE for "namespace:L_fringeTweaker_7_CON.rotateZ"
Traceback (most recent call last):
  File "/studiolibrary/src/mutils/attribute.py", line 260, in type
    self._type = maya.cmds.getAttr(self.fullname(), type=True)
ValueError: No object matches name: namespace:L_fringeTweaker_7_CON.rotateZ # #
```
And the pose is not applied, so I guess it is giving this error for all controllers.
Do you think it would be better to change another thing?

Thanks!

Claudia

**Comment by krathjen** [comment]
Hey @cfujiwara-rfx,

Thanks for the detailed explanation.

I'm wondering if we should change the following line to avoid showing the namespace `:` in the UI.

https://github.com/krathjen/studiolibrary/blob/a66ace2a8f6f7f4e525e7b43eec20d6b6d474ce7/src/mutils/transferobject.py#L168

to

```python
            sceneNamespaces = mutils.namespace.getAll() + [":"]
```

Let me know what you think and thanks again.

Kurt

**Comment by cfujiwara-rfx** [comment]
Hi @krathjen ,
Yeah, this would work too. I submitted a new commit moving the change.
Thank you!
Claudia

**Comment by krathjen** [comment]
Hi @cfujiwara-rfx,

That's great! I'll merge your changes into 2.8.1.

Thanks again for contributing!

Kurt

**Comment by krathjen** [comment]
Ahh.. sorry @cfujiwara-rfx I should have merged your changes instead of a rebase. Thanks for deleting the Branch! :)

**Pull request merged**
