### PR TITLE
Add support for changing the thumbnail after an item has been created

### PR DESCRIPTION
**Pull request by hammenm**
Implementation for the issue #17.

### CODE REVIEW

**Comment by krathjen** [comment]
Hey @hammenm ,

Sorry, that I didn't get back to you on this branch.

I have rebased and resolved the conflicts to the latest master.

I will also look at the issues that you mentioned.

Remeber to pull the latest changes before creating a new commit.

git pull master
git pull feat/change-image-item

**Comment by krathjen** [comment]
Hey @hammenm,

Thanks for making the changes! I like how you refactored the messagebox.py module. :D 

I have also made a few changes to the messagebox file to support the "Dont show again" settings within the warning dialog itself.

This warning dialog can also be used for By Frame dialog in the animitem.

Please let me know if you don't have time to test the latest changes.

Thanks,

Kurt

**Comment by hammenm** [comment]
Hey @krathjen,

Sorry I noticed your progress on this feature only today.

I noticed only a minor issue for pose which do not previously have an image. I commit the file with this minor change.

Otherwise, it seems like everything works as expected, and I don't have the issue with Maya 2016 anymore. You did a great job with the refactoring of the commit and the feature in general !

**Comment by krathjen** [comment]
Sorry, I was away last week. 

I'll try and have a look at the changes soon.

Thanks again! :)

Kurt

**Comment by krathjen** [comment]
Finally merging this request. 

I've enabled this feature for the create widget and we'll enable this feature for the preview widget after a bit more testing.

Thanks again @hammenm for your help.

**Pull request merged**
